version: 0.0
os: linux
files:
  - source: /chatApp
    destination: /home/ubuntu/cds-demo/
permissions:
  - object: /home/ubuntu/cds-demo
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/dependencies.sh
      timeout: 300
      runas: ubuntu
