version: 0.0
os: linux
files:
  - source: /chatApp
    destination: /home/ubuntu/cds-demo/
permissions:
  - object: /home/ubuntu/cds-demo
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 300
      runas: root
      mode: 777
  AfterInstall:
    - location: scripts/dependencies.sh
      timeout: 300
      runas: ubuntu
<<<<<<< HEAD
=======
      mode: 777
    - location: scripts/gunicorn.sh
      timeout: 6000
      runas: ubuntu
      mode: 777
    - location: scripts/required-files.sh
      timeout: 6000
      runas: ubuntu
      mode: 777
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 6000
      runas: ubuntu

>>>>>>> f9dfe481e2c90028a8f4322a7a182904165df839
