version: 0.0
os: linux
files:
  - source: /chatApp
    destination: /home/ubuntu/cds-demo/
permissions:
  - object: /home/ubuntu/cds-demo
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/1.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/dependencies.sh
      timeout: 6000
      runas: ubuntu
    - location: scripts/gunicorn.sh
      timeout: 6000
      runas: ubuntu
    - location: /required-files
      timeout: 6000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 6000
      runas: ubuntu

